### ISSUE TITLE
URL format for `_domainconnect` TXT record is not specified

### ISSUE THREAD

**Issue by unixcharles** [Domain-Connect/spec#1]
The specification mention that `_domainconnect` must return the URL prefix for the REST endpoint. 

```
4.4.  DNS Provider Discovery

   In order to facilitate discovery of the DNS Provider given a domain
   name, a domain will contain a record in DNS.

   This record will be a simple TXT record containing a URL used as a
   prefix for calling a discovery API.  This record will be named
   domainconnect.

   An example of this record would contain:

   https://domainconnect.godaddy.com
```

But the URL format is not specified.

For example, the current implementation in godaddy returns `domainconnect.api.godaddy.com`, which does not include the protocol.

This is problematic because if we want service provider to implement this in a generic matter, the provider needs to know in advance the URL format and how to validate the value in the TXT record.

**Comment by arnoldblinn** [comment]
The protocol is always https:, hence the omission.  Will clarify in the spec.
