### ISSUE TITLE
Merge of SPF-record

### ISSUE THREAD

**Issue by pawel-kow** [Domain-Connect/spec#10]
Imagine there are 2 services configured for one domain, which both can send E-mail from the accounts assigned to the domain name.

Typical setup:
1) Mail service: template with MX and SPF records
2) Newletter service: template with SPF and DKIM configuration

Current conflict resolution in the spec advises to remove service (1) in case service (2) is configured.
This is probably not the intended usage by the customer.

Other option, not to detect conflict will result in 2 SPF records -> broken setup, not conform to RFC (https://tools.ietf.org/html/rfc4408#section-3.1.2)
Similar, if SPF records would be marked as not-essential (see PR #9) it will not brake service (1) but will also only make one of 2 services not failing on SPF-checks.

I think the only viable solution is to define SPF-merge into the standard and define the strategy.

My proposal would be:
Merge everything between "v=spf1" and "all". Chose the highest value for "all" (so from ~all and -all the merged version would show -all).

**Comment by arnoldblinn** [comment]
Seems to me that sometimes people would want some sort of merge and sometimes not.

When would Domain Connect know to “merge” vs. “nuke”?

**Comment by pawel-kow** [comment]
Any use case where Domain Connect shall nuke the template solely based on SPF?

**Comment by pawel-kow** [comment]
I propose simple merging logic. I checked it in the mean time with Mailjet, who implement such logic on their side this way:
-	take “v=spf1” static prefix
-	for all services with SPF record
o	add all the rules to the result in the same order, excluding “all” rule
-	add “all” rule, taking the least (or most tbd) restrictive of “all” rules between the merged templates

If DNS provider supports also “reverse” use-case (explicit or by conflict management) it should also then merge the record again from the remaining templates.

I think also we should go into direction of advising generally SPF records as removable (essential = OnApply), so that in critical cases when the record gets too long or gets too many DNS lookups (standard defines 10) the customer could fix it without dropping all related templates from DNS.

@arnoldblinn , @FlorentinStafie  would love to know your opinion/remarks so I can draft the change to the spec.

**Comment by pawel-kow** [comment]
Just re-opening to keep open until final wording lands in the spec.

@FlorentinStafie, just 2 comments on your questions
Re 1) Current implementation does not override, as it detect conflict -> in result one of the templates will stay the other will be removed as whole (template consistency principle we follow)
Overwrite is also not good as then only one of 2 providers will be able to send E-mails

Re 2) I could find arguments in both directions. If any of providers define ? or ~ rule, it means he had a reason for that (as mentioned by @arnoldblinn is asking for trouble, but SPF is in some areas so dark that I don't dare to claim I know all corner cases). In this sense "upgrading" his rule to - may mean that these E-mails are not delivered and this service is affected. "Least restrictive" would offer less protection but is likely to cause less issues.

I think manual intervention on an SPF, by removing rules of one of service providers shall be explicitly allowed by him (using essential = OnApply), otherwise following again template consistency principle I would not offer it.
