### ISSUE TITLE
Content type not specified to get access_token

### ISSUE THREAD

**Issue by pawel-kow** [Domain-Connect/spec#21]
https://github.com/Domain-Connect/spec/blob/master/Domain%20Connect%20Spec%20Draft.adoc#433-oauth-flow-requesting-an-access-token

> The following table describes the POST parameters to be included in the request for the access token. The parameters should be accepted via the query string or the body of the post. This is again particularly important for the client_secret, as passing secrets via a query string is generally frowned upon given that various systems often log URLs.

Here we shall say more about accepted encoding (both input and output).

So far we assumed we only need "application/json", but one of providers requested "application/x-www-form-urlencoded" as well.

**Comment by arnoldblinn** [comment]
Added documentation to the spec that we only support application/json.
