### ISSUE TITLE
Record type specified for discovery does not match records at GoDaddy

### ISSUE THREAD

**Issue by sql-sith** [Domain-Connect/spec#36]
The current draft spec (https://github.com/Domain-Connect/spec/blob/master/Domain%20Connect%20Spec%20Draft.adoc#spf-record-merging) says that the discovery record for `_domainconnect.mydomain.com` should be a `TXT` record in the `mydomain.com` zone. However, my domains have a `CNAME` record instead at GoDaddy. Either the draft spec is wrong or GoDaddy's implementation is non-compliant. 

Here is an example using `databaseguy.com` that shows that there is not a `TXT` record for `_domainconnect` but there is a `CNAME` record for it.

![image](https://user-images.githubusercontent.com/1082694/56837288-811e8480-683f-11e9-8109-fa027bfa8945.png)

**Comment by arnoldblinn** [comment]
The spec actually says that it should respond to a TXT record query.

Directly from the spec:

As a practical matter of implementation, the DNS Provider may or may not contain a copy of this data in each and every zone. Instead, the DNS Provider must simply respond to the DNS query for the _domainconnect TXT record with the appropriate data.

How this is implemented is up to the DNS Provider.

For example, the DNS Provider may not store the data inside a TXT record for the domain, opting instead to put a CNAME in the zone and have the TXT record in the target of the CNAME. Another DNS Provider may simply respond with the appropriate records at the DNS layer without having the data in each zone.

The URL prefix returned is subsequently used by the Service Provider to determine the additional settings for using Domain Connect on this domain at the DNS Provider. This is done by calling a REST API.

**Comment by sql-sith** [comment]
Hi Arnold, and thanks for the reply. I didn't read the whole spec, but I did look at every reference to TXT records, including the one you cite. I may be misunderstanding your first sentence, but it looks like you're saying that the DNS system should respond to a TXT query for _domainconnect. If so, that's exactly what I'm saying. 

My example shows that querying for TXT records for the databaseguy.com zone does _not_ return _domainconnect record. It does not matter if I explicitly request the _domainconnect record or just request all the TXT records. 

Rather, i order to get the _domainconnect record, I either have to query it as a string without a record type (eg: `dig _domainconnect.databaseguy.com.`) or specifically as a CNAME (`dig CNAME _domainconnect.databaseguy.com.`). So the GoDaddy implementation does not "respond to the DNS query for the _domainconnect TXT record," as the spec states.

So I see one of two situations here. If, as I believe, the correct meaning of a "DNS query for the _domainconnect TXT record" is that a resolver specifies both type=TXT and label=_domainconnect, then GoDaddy's implementation is not compliant because it will not return the _domainconnect information for such a query. 

However, if that phrase it is supposed to mean that discovery can occur by querying the _domainconnect label within the zone, then the wording is misleading and I think it should be edited to say something like this:

> As a practical matter of implementation, the DNS Provider may or may not contain a copy of this data in each and every zone. Instead, the DNS Provider must simply respond to DNS queries against the zone for the name "_domainconnect" with the appropriate data.

**Comment by pawel-kow** [comment]
Hi @sql-sith,

Everything is OK, you just need to query TXT on `_domainconnect.databaseguy.com` not `databaseguy.com`. Using CNAME for the record, which in results returns required TXT is just an implementation choice that is fully in compliance with DNS spec and part of normal DNS resolution. We do the same at 1&1 IONOS.
```
root@localhost:~# dig +noadditional +noauthority TXT _domainconnect.databaseguy.com.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +noadditional +noauthority TXT _domainconnect.databaseguy.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49481
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 8, ADDITIONAL: 17

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_domainconnect.databaseguy.com.        IN      TXT

;; ANSWER SECTION:
_domainconnect.databaseguy.com. 3510 IN CNAME   _domainconnect.gd.domaincontrol.com.
_domainconnect.gd.domaincontrol.com. 3510 IN TXT "domainconnect.api.godaddy.com"
```

**Comment by sql-sith** [comment]
@arnoldblinn / @pawel-kow, thank you both for setting me straight. I can now simultaneously hang my head in embarrassed shame for lack of knowledge, but hold that same head high for (finally) beginning to learn about the domain connect spec.
