### ISSUE TITLE
Remove domain record

### ISSUE THREAD

**Issue by SirPrikol** [Domain-Connect/spec#59]
Good afternoon, I can not delete the record created through domainconnect, as a result of the ns server the cloudflare is given WRONG ip addresses

The entries were changed 2 days ago, all ns servers, except for the cloudflare, are given correctly

**Comment by arnoldblinn** [comment]
I don’t understand what you are asking for here.

Domain Connect doesn’t support a delete operation; it is not intended as a crud API.

And I’m not sure what you are saying is happening with respect to CloudFlare…..

From: SirPrikol ***@***.***>
Sent: Sunday, March 14, 2021 11:54 AM
To: Domain-Connect/spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Domain-Connect/spec] Remove domain record (#59)


Good afternoon, I can not delete the record created through domainconnect, as a result of the ns server the cloudflare is given WRONG ip addresses

The entries were changed 2 days ago, all ns servers, except for the cloudflare, are given correctly

**Comment by pawel-kow** [comment]
@SirPrikol  this seems to be a specific issue to Cloudflare, not a spec issue to Domain Connect. Please reach out to Cloudflare to clarify.
